// Generated by CoffeeScript 1.10.0
var Utility;

Utility = (function() {
  function Utility() {}

  Utility.addComma = function(num) {
    return String(num).replace(/(\d)(?=(\d\d\d)+(?!\d))/g, '$1,');
  };

  Utility.rand = function(min, max) {
    return Math.floor(Math.random() * (max - min + 1)) + min;
  };

  Utility.addressBar = function(url) {
    return window.history.replaceState('', '', '' + url);
  };

  return Utility;

})();
